baseURL = "http://example.org/"
languageCode = "en-us"
title = "DSG | IIT Roorkee"

# Site Menu
[menu]
    # Navbar Menu
    [[menu.nav]]
        name    = "Work"
        url     = "work"
        weight  = 2
    [[menu.nav]]
        name    = "Events"
        url     = "events"
        weight  = 3
    [[menu.nav]]
        name    = "Blogs"
        url     = "blogs"
        weight  = 4
    [[menu.nav]]
        name    = "About"
        url     = "about"
        weight  = 5

# Site Params
[params]
    home = "Home"
    logo = "images/dsg.png"
    dateFormat = "28 July 1999"
    # Meta data
    author = "DSG"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.svg"
        heading = "Data Science Group"
        description = "DSG is an umbrella group Which comes under SDS(Software Development Section).It is a student group that constantly tries to learn and foster technical activities in campus."
        [[params.banner.flipText]]
            title   = "IIT Roorkee, India"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT US"
        content = "Hello, We are DSG(Data Science Group) IITR, an umbrella group Which comes under SDS(Software Development Section).We are a student group that constantly tries to learn and foster technical activities in campus. Our members work in Machine Learning, Deep Learning, Reinforcement Learning and sometimes even in complex topic like Graph Networks. <br> <br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, adipisci voluptatum repudiandae, natus impedit repellat aut officia illum at assumenda iusto reiciendis placeat. Temporibus, vero."
        image   = "images/about/aboutTeam.jpeg"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Latest Projects"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    [params.footer]
        [[params.footer.socialIcon]]
            icon = "ion-social-facebook"
            url = "#"

        [[params.footer.socialIcon]]
            icon = "ion-social-github"
            url = "#"

        [[params.footer.socialIcon]]
            icon = "ion-social-linkedin"
            url = "#"
