baseURL = "/"
languageCode = "en-us"
title = "DSG | IIT Roorkee"
summaryLength = 30
paginate = 3
publishDir = "docs"

# Site Menu
[menu]
    # Navbar Menu
    [[menu.nav]]
        name    = "Work"
        url     = "/#works"
        weight  = 2
    [[menu.nav]]
        name    = "Events"
        url     = "events"
        weight  = 3
    [[menu.nav]]
        name    = "Blogs"
        url     = "blogs"
        weight  = 4
    [[menu.nav]]
        name    = "About"
        url     = "about"
        weight  = 5

# Site Params
[params]
    home = "Home"
    logo = "images/dsg.png"
    cerebro = "images/cerebro.png"
    cerebroBack = "images/cerebroBack.svg"
    dateFormat = "28 July 1999"
    # Meta data
    author = "DSG"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.svg"
        heading = "Data Science Group, IIT Roorkee"
        projectLink = "#works"
        scroll = "images/scroll.svg"
        down = "images/down.svg"
        description = "A student organization Driving innovation via Machine Learning. Code | Train | Predict"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "About"
        content = "We are Data Science Group, IIT Roorkee. A student organizaton and a part of the umbrella organization Software Development Section. We aim to work on innovative open source projects in the domain of Machine Learning, bridging the gap between research and industry. In the process, we fullfil our mission of cultivating and evolving the technical community in Roorkee by organizing lectures, workshops, hackathons spanning across the field of Machine Learning, Deep Learning and Data Science in general."
        image   = "images/about/aboutTeam.jpeg"

    # work Section On Homepage
    [params.work]
        enable  = true
        title   = "Projects"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    [params.footer]
        [[params.footer.socialIcon]]
            icon = "ion-social-facebook"
            url = "#"

        [[params.footer.socialIcon]]
            icon = "ion-social-github"
            url = "#"

        [[params.footer.socialIcon]]
            icon = "ion-social-linkedin"
            url = "#"

        [[params.footer.ccIcon]]
            icon = "ion-closed-captioning"
            url = "#"
        
        [[params.footer.locationIcon]]
            icon = "ion-ios-location"
            url = "#"